[Interface]
Address = 10.13.13.2
PrivateKey = EDHX4gOZNcfa9ULJzEJgu0vyj1orkhx5xkcQIRW7iWo=
ListenPort = 51820
DNS = 192.168.1.147

[Peer]
PublicKey = gx1PrfBVQO8/zOUNJfZgMypizmreRnYvMC+7+Xd46Tg=
PresharedKey = hw9STOOBlENB8SpE1NGw5+oD2uDbJUW/4w5Sim0KFHg=
Endpoint = 192.168.1.147:51820
AllowedIPs = 0.0.0.0/0
