server {
    listen 443 ssl;
    server_name siem.local;

    ssl_certificate /etc/nginx/certs/siem.crt;
    ssl_certificate_key /etc/nginx/certs/siem.key;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
