[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = iBQf2U67T5s/IM7oCJhMebjkUgT1snGNZXPphrMe91M=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = larfj2mFRf+/ncvqMyIa/l+xcErXsOQy1o2OfT80FCs=
PresharedKey = hw9STOOBlENB8SpE1NGw5+oD2uDbJUW/4w5Sim0KFHg=
AllowedIPs = 10.13.13.2/32

[Peer]
# peer2
PublicKey = nEdGJawvRWFxvNLCgq9vuFonZX87Bp/G5iBnK+G5Jj0=
PresharedKey = A3lBUlBjZmOeYQzg1rO3ei/QKhfJgluRsxVR4i3/s0Q=
AllowedIPs = 10.13.13.3/32

[Peer]
# peer3
PublicKey = 35dwuTFVm9TlCpUi7FEy4vmnUBJQho0ujU2cIksLzBA=
PresharedKey = vqEMFsoH+lhLHq+Y7GfaL4JBi6SZz1OOlwnQ+6l+Idc=
AllowedIPs = 10.13.13.4/32

