[Interface]
Address = 10.13.13.3
PrivateKey = 4G+WQSUG5FohjwZCQTDFiasN5YVCyu022vsvVjhNcnQ=
ListenPort = 51820
DNS = 192.168.1.147

[Peer]
PublicKey = gx1PrfBVQO8/zOUNJfZgMypizmreRnYvMC+7+Xd46Tg=
PresharedKey = A3lBUlBjZmOeYQzg1rO3ei/QKhfJgluRsxVR4i3/s0Q=
Endpoint = 192.168.1.147:51820
AllowedIPs = 0.0.0.0/0
