[Interface]
Address = 10.13.13.4
PrivateKey = iGCTr9w1OlnOLhkAhU1mpChImfX1WNGkWqKuz+lDBW8=
ListenPort = 51820
DNS = 192.168.1.147

[Peer]
PublicKey = gx1PrfBVQO8/zOUNJfZgMypizmreRnYvMC+7+Xd46Tg=
PresharedKey = vqEMFsoH+lhLHq+Y7GfaL4JBi6SZz1OOlwnQ+6l+Idc=
Endpoint = 192.168.1.147:51820
AllowedIPs = 0.0.0.0/0
